# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0002_auto_20170904_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spec',
            new_name='spec_types',
        ),
    ]
