# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:14
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0002_auto_20170817_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'USD', b'Dolars'), (b'EUR', 'Euro'), (b'VND', b'Vietnam Dong')], default=b'USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'USD', b'Dolars'), (b'EUR', 'Euro'), (b'VND', b'Vietnam Dong')], default=b'USD', editable=False, max_length=3),
        ),
    ]
