# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0002_auto_20170630_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'prjimages/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='agencymember',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='econ.BaseUser'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='baseuser_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'prjimages/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'prjimages/%Y/%m/%d/%H/%M/%S/'),
        ),
    ]
