# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0002_auto_20170705_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cagetory',
            old_name='cagetory_parent',
            new_name='parent',
        ),
    ]
