# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 09:41
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0002_auto_20170716_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', 'Euro'), (b'USD', 'US Dollar'), (b'VND', b'Vietnam Dong')], default=b'USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', 'Euro'), (b'USD', 'US Dollar'), (b'VND', b'Vietnam Dong')], default=b'USD', editable=False, max_length=3),
        ),
    ]
