# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0003_auto_20170630_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='productdetail_spec',
        ),
    ]
