# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0003_auto_20170629_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econ.Agency')),
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='baseuser_gender',
            field=models.CharField(choices=[(b'U', b'Unknow'), (b'M', b'Male'), (b'F', b'Female')], default=b'U', max_length=1),
        ),
        migrations.AddField(
            model_name='agencymember',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='econ.BaseUser'),
        ),
        migrations.AddField(
            model_name='agencymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econ.BaseUser'),
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_member',
            field=models.ManyToManyField(through='econ.AgencyMember', to='econ.BaseUser'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='econ.Agency'),
            preserve_default=False,
        ),
    ]
