# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 09:42
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0003_auto_20170718_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
