# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0003_auto_20170705_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.ManyToManyField(related_name='product', to='econ.ProductSpecificDetail'),
        ),
    ]
