# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0003_auto_20170724_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedinfo',
            name='content_type',
        ),
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cagetory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cagetory',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TaggedInfo',
        ),
    ]
