# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0004_auto_20170629_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quatity',
            field=models.IntegerField(default=0, verbose_name=b'numbers'),
        ),
        migrations.AlterField(
            model_name='agencymember',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='econ.BaseUser'),
        ),
    ]
