# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0004_auto_20170706_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecific',
            name='specific_unit',
        ),
        migrations.RemoveField(
            model_name='productspecificdetail',
            name='detail_desc',
        ),
    ]
