# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0004_remove_productdetail_productdetail_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='productdetail_detail',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='productdetail_prod',
        ),
        migrations.AddField(
            model_name='product',
            name='product_detail',
            field=models.ManyToManyField(to='econ.ProductSpecificDetail'),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
