# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0004_auto_20170718_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='econ.Product')),
                ('info', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
