# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0005_auto_20170706_0437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSpecific',
            new_name='Specific',
        ),
        migrations.RenameModel(
            old_name='ProductSpecificDetail',
            new_name='SpecificDetail',
        ),
    ]
