# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0006_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=100)),
                ('promotion_type', models.CharField(choices=[(b'M', b'Minus'), (b'P', b'Percentage'), (b'O', b'Offer')], default=b'P', max_length=1)),
                ('promotion_value', models.FloatField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econ.Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=100)),
                ('promotion_type', models.CharField(choices=[(b'M', b'Minus'), (b'P', b'Percentage'), (b'O', b'Offer')], default=b'P', max_length=1)),
                ('promotion_value', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econ.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
