# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0006_auto_20170825_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_agency',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_cagetory',
            new_name='cagetory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price_currency',
            new_name='price_currency',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_quatity',
            new_name='quatity',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='product_price_currency',
            new_name='price_currency',
        ),
    ]
