# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0006_auto_20170706_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econ.Product')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econ.SpecificDetail')),
            ],
        ),
    ]
