# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0007_auto_20170629_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencypromotion',
            old_name='agency',
            new_name='apply_to',
        ),
        migrations.RemoveField(
            model_name='productpromotion',
            name='product',
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='apply_to',
            field=models.ManyToManyField(to='econ.Product'),
        ),
    ]
