# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0007_auto_20170825_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slug',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='slug',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
