# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0007_productspecdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_detail',
        ),
    ]
