# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0008_remove_product_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecdetail',
            name='specof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='econ.Specific'),
        ),
    ]
