# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0008_taggedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedinfo',
            name='tags',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
