# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0008_auto_20170629_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_logo',
            field=models.ImageField(null=True, upload_to=b'prjimages/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AddField(
            model_name='agencypromotion',
            name='promotion_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agencypromotion',
            name='promotion_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='baseuser_avatar',
            field=models.ImageField(null=True, upload_to=b'prjimages/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(null=True, upload_to=b'prjimages/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='promotion_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='promotion_start',
            field=models.DateTimeField(null=True),
        ),
    ]
