# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0009_auto_20170825_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='agency_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='agency_member',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='agency_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_sym',
            new_name='sym',
        ),
        migrations.RenameField(
            model_name='cagetory',
            old_name='cagetory_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agency_id',
        ),
    ]
