# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0009_auto_20170720_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='cagetory',
            name='optiontype',
            field=models.IntegerField(choices=[(1, b'Inherit'), (2, b'Option by specify'), (3, b'Option by generic')], default=1),
        ),
    ]
