# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0009_productspecdetail_specof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecdetail',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productspecdetail',
            name='specof',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='econ.Specific'),
            preserve_default=False,
        ),
    ]
