# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0010_auto_20170825_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencypromotion',
            old_name='promotion_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='agencypromotion',
            old_name='promotion_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='agencypromotion',
            old_name='promotion_type',
            new_name='promotiontype',
        ),
        migrations.RenameField(
            model_name='agencypromotion',
            old_name='promotion_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='agencypromotion',
            old_name='promotion_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='baseuser_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='baseuser_avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='baseuser_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='baseuser_birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='baseuser_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='productoptionimage',
            old_name='image_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='productpromotion',
            old_name='promotion_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='productpromotion',
            old_name='promotion_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productpromotion',
            old_name='promotion_type',
            new_name='promotiontype',
        ),
        migrations.RenameField(
            model_name='productpromotion',
            old_name='promotion_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='productpromotion',
            old_name='promotion_value',
            new_name='value',
        ),
    ]
