# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0010_auto_20170706_0837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecdetail',
            unique_together=set([('specof', 'prod')]),
        ),
        migrations.AlterUniqueTogether(
            name='specific',
            unique_together=set([('specific_name', 'specific_of')]),
        ),
    ]
