# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0011_auto_20170828_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseUser',
            new_name='Customer',
        ),
    ]
