# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0011_auto_20170707_0722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specificdetail',
            unique_together=set([('detail_field', 'detail_value')]),
        ),
    ]
