# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0012_auto_20170828_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='agency',
        ),
    ]
