# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0012_auto_20170707_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'media/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econ.Product'),
        ),
    ]
