# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0013_remove_product_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='quatity',
            field=models.IntegerField(default=0),
        ),
    ]
