# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0015_cagetory_allow_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cagetory',
            name='allow_choose',
            field=models.BooleanField(default=True),
        ),
    ]
