# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0016_auto_20170829_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isvariety',
            field=models.BooleanField(default=True),
        ),
    ]
