# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econ', '0019_auto_20170713_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='prod',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='econ.Product'),
        ),
    ]
